### ISSUE TITLE
kf5-kdoctools fails to build: Can't create '/usr/local/Cellar/perl/5.26.0/lib/perl5/site_perl/5.26.0/Test'

### ISSUE THREAD

**Issue by diversys** [haraldF/homebrew-kf5#126] opened 2017-08-01 16:56 UTC
```
--> Working on URI
Fetching http://www.cpan.org/authors/id/E/ET/ETHER/URI-1.72.tar.gz ... OK
Configuring URI-1.72 ... OK
==> Found dependencies: Test::Needs
--> Working on Test::Needs
Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Test-Needs-0.002005.tar.gz ... OK
Configuring Test-Needs-0.002005 ... OK
Building and testing Test-Needs-0.002005 ... ! Installing Test::Needs failed. See /private/tmp/kf5-kdoctools-20170801-38353-1q7clj2/kdoctools-5.36.0/.brew_home/.cpanm/work/1501605588.38369/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Test::Needs' is not installed
! Bailing out the installation for URI-1.72.
FAIL
```
```
Manifying 1 pod document
Appending installation info to /usr/local/Cellar/perl/5.26.0/lib/perl5/5.26.0/darwin-thread-multi-2level/perllocal.pod
/bin/sh: /usr/local/Cellar/perl/5.26.0/lib/perl5/5.26.0/darwin-thread-multi-2level/perllocal.pod: Operation not permitted
make: [doc_site_install] Error 1 (ignored)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Can't create '/usr/local/Cellar/perl/5.26.0/lib/perl5/site_perl/5.26.0/Test'
mkdir /usr/local/Cellar/perl/5.26.0/lib/perl5/site_perl/5.26.0: Operation not permitted at /usr/local/Cellar/perl/5.26.0/lib/perl5/5.26.0/ExtUtils/Install.pm line 477.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 at -e line 1.
make: *** [pure_site_install] Error 1
-> FAIL Installing Test::Needs failed. See /private/tmp/kf5-kdoctools-20170801-40985-v8rsa2/kdoctools-5.36.0/.brew_home/.cpanm/work/1501606400.41001/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'Test::Needs' is not installed
-> FAIL Bailing out the installation for URI-1.72.
```
```
ls -l /usr/local/Cellar/perl/5.26.0/lib/perl5/
total 0
drwxr-xr-x  128 diver  admin  4352 Aug  1 18:16 5.26.0
drwxr-xr-x    2 diver  admin    68 Aug  1 19:49 site_per
```
```
brew doctor
Your system is ready to brew.
```

`sudo chown -R "$USER":admin /usr/local` didn't help.

**Comment by diversys** [comment] 2017-08-01 22:05
I narrowed it down to `system "cpanm", "URI"`
Apparently, brew fails to write to `/usr/local/lib` from sandbox, while  running `cpanm URI` outside of sandbox has no problems with installation.

I also had to `mkdir /usr/local/lib/kde5/libexec` (outside of sandbox) for this Formula to work.

**Comment by yurikoles** [comment] 2017-08-02 11:15
@diversys I confirm this problem. Installing URI module via terminal did the trick.

**Comment by diversys** [comment] 2017-08-02 17:50
So it seems that `/usr/local` is write protected with sudo. I wonder how other formulas work then?

```
grep local /System/Library/Sandbox/rootless.conf
*				/usr/local
```

**Comment by yurikoles** [comment] 2017-08-27 18:37
Closing as duplicate of more recent and detailed issue: #127

**Closed** 2017-08-27 18:36 UTC
