### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by rlober** [haraldF/homebrew-kf5#128] opened 2017-08-05 11:16 UTC
Hey there, 

Been trying to get kdevelop installed but I keep running into the same `Operation not permitted` issues e.g.

```
Error: Operation not permitted - (/usr/local/Cellar/kf5-kconfig/5.36.0/lib/kde5/libexec/kconf_update, /usr/local/lib/kde5/libexec/kconf_update)
```

The first one was: 
```
Error: Operation not permitted /usr/local/lib/kde5
```
so I just made the directory manually, `mkdir /usr/local/lib/kde5`. This got me a little further...
```
Error: Operation not permitted /usr/local/lib/kde5/libexec
```
so I made the `libexec` dir. But got the same error. 
I ran a `sudo chow -R [user] /usr/lib/kde5/` and that got me to my current error:
```
Error: Operation not permitted - (/usr/local/Cellar/kf5-kconfig/5.36.0/lib/kde5/libexec/kconf_update, /usr/local/lib/kde5/libexec/kconf_update)
```

I have a lot of packages installed with `brew` and I don't see why ownership would be an issue but admittedly I am not very well versed in the internals of `brew` so I don't really know where to go from here. 

Thanks in advance for any help and let me know if you need more info.

**Comment by yurikoles** [comment] 2017-08-05 12:15
duplicate of #127

**Closed by yurikoles** 2017-08-05 12:15 UTC

**Comment by rlober** [comment] 2017-08-05 13:15
@yurikoles 
Apologies. I didn't see #127 when searching the issues.
